#!/usr/bin/env bash
# Download test fixtures for integration tests
set -euo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)/tests/fixtures"
mkdir -p "$DIR"

echo "Downloading test fixtures to $DIR..."

# Create a simple test image (1x1 white PNG)
if command -v python3 &>/dev/null; then
  python3 -c "
import struct, zlib, base64
# Minimal valid PNG: 1x1 white pixel
def create_png(path):
    # PNG header
    sig = b'\\x89PNG\\r\\n\\x1a\\n'
    # IHDR
    ihdr_data = struct.pack('>IIBBBBB', 1, 1, 8, 2, 0, 0, 0)  # 1x1, 8bit RGB
    ihdr_crc = zlib.crc32(b'IHDR' + ihdr_data)
    ihdr = struct.pack('>I', 13) + b'IHDR' + ihdr_data + struct.pack('>I', ihdr_crc & 0xffffffff)
    # IDAT
    raw = zlib.compress(b'\\x00\\xff\\xff\\xff')  # filter byte + white pixel
    idat_crc = zlib.crc32(b'IDAT' + raw)
    idat = struct.pack('>I', len(raw)) + b'IDAT' + raw + struct.pack('>I', idat_crc & 0xffffffff)
    # IEND
    iend_crc = zlib.crc32(b'IEND')
    iend = struct.pack('>I', 0) + b'IEND' + struct.pack('>I', iend_crc & 0xffffffff)
    with open(path, 'wb') as f:
        f.write(sig + ihdr + idat + iend)

create_png('$DIR/sample-image.png')
print('Created sample-image.png')
" 2>/dev/null || echo "Could not create test image via python3"
fi

# Create a README for fixtures
cat > "$DIR/README.md" << 'EOF'
# Test Fixtures

These files are used for integration and e2e tests.

- `sample-image.png` — minimal 1x1 white PNG for basic tests
- `sample-audio-10s.wav` — 10-second WAV file (provide manually)
- `sample-video-30s.mp4` — 30-second MP4 clip (provide manually)
- `sample-doc-5p.pdf` — 5-page PDF document (provide manually)

For full integration tests, you need to provide the larger media files.
The minimal image is auto-generated by `fetch-fixtures.sh`.
EOF

echo "Fixtures ready."
echo "Note: For full integration tests, provide sample-audio-10s.wav, sample-video-30s.mp4, and sample-doc-5p.pdf manually."
